server:
  port: 8801

eureka:
  client:
    serviceUrl:
      defaultZone: http://woo-eureka:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zhouyang2019/springcloudConfig
          searchPaths: woo
          clone-on-start: true
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      client:
        url: http://woo-admin:9301 #配置admin-server地址
  zipkin:
    base-url: http://woo-zipkin:9411
  sleuth:
    sampler:
      probability: 0.1 #设置Sleuth的抽样收集概率
